sudo: required
language: php
dist: bionic

php:
  - 7.4

before_install:
  - sudo add-apt-repository -y ppa:ondrej/php
  - sudo apt-get -y update
#  - sudo apt-get -y --allow-unauthenticated upgrade
  - sudo apt-get -y install php7.4-zip
#  - export CHROME_BIN=chromium-browser

install:
  - travis_retry composer install --no-interaction

#services:
#  - xvfb

before_script:
#  - export DISPLAY=:99.0
#  - sh -e /etc/init.d/xvfb start
#  - sleep 3
#  - ./vendor/laravel/dusk/bin/chromedriver-linux &
#  - cp .env.testing .env
  - php artisan serve > /dev/null 2>&1 &

script:
#  - php artisan dusk
  - ./vendor/bin/phpunit
